env:
  global:
    - CC_TEST_REPORTER_ID=86ef0a64fc4fca294fbe57ec0d25e12c94737d5d68c70378581f5a5c5bb98a99
language: node_js
node_js:
  - "10"
install: npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm install -g npm
  - npm install -g gulp
  - npm install -g greenkeeper-lockfile
  - greenkeeper-lockfile-update
script:
  - gulp build
  - gulp lint
  - gulp test
  - gulp coverage
after_script:
  - ./cc-test-reporter after-build --prefix /coverage --exit-code $TRAVIS_TEST_RESULT
  - greenkeeper-lockfile-upload
